nombre = input("ingrese su nombre: ")
edad = input("ingrese su edad: ")
altura = input("ingrese su altura: ")
ciudad = input("ingrese su ciudad: ")
direccion = input("ingrese su direccion: ")
pais = input("ingrese su pais: ")
estudio = input("ingrese sus nivel de educación: ")
lavoral = input("ingrese su experiencia lavoral: ")
usuario = tuple((nombre, edad, altura))
direccion = tuple((ciudad, direccion, pais))
educacion = tuple((estudio))
experienciaLabora = tuple((lavoral))

print(f"""la informacion sobre el usurio es:{usuario[0]}""")
print(f"""la informacion sobre la educacion del usuario es:{educacion[0]}""")
print(f"""la informacion sobre la direccion del usuario es:{direccion[0]}""")
print(f"""la informacion sobre la experiencia laboral es:{experienciaLabora[0]}""")

